server:
  port: 8900 #端口号
spring:
  application:
    name: consumer-hystrix
eureka:
  client:
    serviceUrl: #大坑，要注意层级千万不要把下边的层级和上边写一块了
      defaultZone: http://user:1234@localhost:10000/eureka/

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://user:1234@localhost:10000/eureka/

